Revision of all labs for the latest UI in Azure
MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure pull request #10
Opened 2020-12-11 16:28 UTC by alistairmatthews

Ready for review.

2020-12-23 00:26 UTC, kalendelaney commented on Instruction/dp-050-01_instructions.md
> -1. from the Define workloads section ensure that there are no workloads in the **Servers** Section
I didn't have anything in the Server section, but I did have something in the Databases section.

2020-12-23 00:27 UTC, kalendelaney commented on Instruction/dp-050-01_instructions.md
> -1. In the **Databases** workload section, click on the **+ Add database** hyperlink.
When I opened the calculator, an existing database was already showing and I could not find the Add database link.

2020-12-23 00:28 UTC, kalendelaney commented on Instruction/dp-050-01_instructions.md
> -   - SQL Server 2008/2008R2 **True**
This is not a TRUE/FALSE option, it is a slider.

2020-12-23 00:31 UTC, kalendelaney commented on Instruction/dp-050-01_instructions.md
> +    | SQL Server 2008/2008R2 | Selected |
What does "selected" mean? This is a slider

2020-12-23 00:37 UTC, kalendelaney commented on Instruction/dp-050-01_instructions.md
> +1. Under **Geo-redundant storage (GRS)**, ensure that **GRS replicates your data to a secondary region that is hundreds of miles away from the primary region** is not selected.
You bolded the name of the option which on first glance makes it seem like something we want. The fact that you said "not" selected could get overlooked.

2020-12-23 00:38 UTC, kalendelaney commented on Instruction/dp-050-01_instructions.md
> +1. Under **Virtual Machine costs**, ensure that **Enable this for the Calculator to not recommend B-series virtual machines** is not selected.
You bolded the name of the option which on first glance makes it seem like something we want. The fact that you said "not" selected could get overlooked.

2020-12-23 15:20 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> -1. from the Define workloads section ensure that there are no workloads in the **Servers** Section
This is what I see by default:
![image](https://user-images.githubusercontent.com/41286777/103011790-6a5b9400-4532-11eb-9728-6b8af7990b8a.png)

2020-12-23 15:23 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> -1. from the Define workloads section ensure that there are no workloads in the **Servers** Section
If you don't see anything, it's because you never used the tool before. I think the step should remain in place, in case the student has something there.

2020-12-23 15:24 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> -1. In the **Databases** workload section, click on the **+ Add database** hyperlink.
Same issue as above. I've added a step to delete anything that's already there.

2020-12-23 15:47 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +    | SQL Server 2008/2008R2 | Selected |
Fixed. See previous response.

2020-12-23 15:53 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Under **Geo-redundant storage (GRS)**, ensure that **GRS replicates your data to a secondary region that is hundreds of miles away from the primary region** is not selected.
It has to be bolded really to show that it's a UI element. I've updated the wording to reflect that it's a slider.

2020-12-23 15:54 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Under **Virtual Machine costs**, ensure that **Enable this for the Calculator to not recommend B-series virtual machines** is not selected.
See previous reponse.

2020-12-23 16:52 UTC, llarkan requested changes
This looks great, and I see that others have already provided some terrific feedback! My comments are based upon the changes that have already been proposed.

I'm new to proposing changes in GitHub, and I'm sorry for the additional work that it must create for the approvers.

Thanks.

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +The main tasks for this exercise are:
The main tasks for this exercise are the following:

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
>  1. Open the Microsoft Total Cost of Ownership (TCO) Calculator
Can you please correct the numbering here and throughout the file?

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Open your browser and navigate to [Azure TCO Calculator](https://azure.microsoft.com/pricing/tco/calculator/).
Here is another place where the numbering is incorrect. 

Also, can you please format this so that it has the "T" tool that enables the text to be easily pasted into the browser address bar inside of the virtual environment?
Thank you.

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
Can you please put a lowercase P in "on-Premises" and change it to "on-premises workload"?

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
>  1. Choose any method of your choice to determine how much memory is being used on the server.
Use a method of your choice to determine the amount of memory being used by the server.

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Choose any method of your choice to determine how CPU resources are being used on the server.
Use a method of your choice to determine ...

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Choose any method of your choice to determine the disk configuration that is configured on the server.
Use a method of your choice to determine...

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +      The customer has an application that uses many databases currently residing in an on-premises version of Microsoft SQL Server 2008. The total database footprint is large at 12 TB, and rapidly g
The existing SAN storage, which contains the databases, is almost at capacity, expensive to expand, and nearing the end of its life.

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +      The customer in this example has a SQL Server that stores databases that fulfil departmental needs. The server on which the databases are hosted is a quad core server, with 16 GB of memory, and
The server on which the databases are hosted is a quad-core server with 16 GB of memory that is used as a backend to simple data access for spreadsheets and an Access form.

2020-12-23 16:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +After completing this exercise, you have identified the appropriate database technologies to migrate to.
After completing this exercise, you will have identified the appropriate Azure technologies for database your migration project.

2020-12-23 17:41 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> -1. navigate to [Azure TCO Calculator](https://azure.microsoft.com/en-us/pricing/tco/calculator/)
1. Open your browser.
2. Navigate to [Azure TCO Calculator](https://azure.microsoft.com/en-us/pricing/tco/calculator/).	
3. From the Define your workloads section, ensure that there are no workloads listed under Servers.

2020-12-23 17:48 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +    | SQL Server 2008/2008R2 | Selected |
@alistairmatthews  - This is a great activity!
@kalendelaney  - I'm loving your recommended changes. As I was going back through the original lab file, I noticed a place that needed a small adjustment, and as I started to enter my proposed change, I noticed that you had already proposed a similar but better one!

2020-12-23 18:14 UTC, llarkan commented on Instruction/dp-050-02_instructions.md
> +You are the senior data engineer of AdventureWorks and are preparing for a data modernization project. You will begin by performing an inventory of the SQL Servers that exist in your environment usin
What about...
One of your on-premises SQL Servers is used to process sales for the business, and you want to ensure that your new Azure services can support your workload after it is migrated.

2020-12-23 18:23 UTC, llarkan commented on Instruction/dp-050-02_instructions.md
> -1. Open up your web browser and go to the [Microsoft Assessment and Planning Toolkit download site](https://www.microsoft.com/en-us/download/details.aspx?id=7826)
Can you please format this so that it has the "T" tool that enables the text to be easily pasted into the browser address bar inside of the virtual environment?

Open up your web browser and go to the [Microsoft Assessment and Planning Toolkit download site](https://www.microsoft.com/en-us/download/details.aspx?id=7826)

Thank you.

2020-12-23 18:24 UTC, llarkan commented on Instruction/dp-050-02_instructions.md
> -1. On the windows desktop, click on **Start**, and type Microsoft Assessment, then click on **Microsoft Assessment and Planning Toolkit**
How about...

1. On the Windows desktop, click **Start**, and type Microsoft Assessment. Then click **Microsoft Assessment and Planning Toolkit**

2020-12-23 19:06 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. In the **Name** textbox, type **Accounting Local Disks**, and then enter these values:
How about this:

2. Enter these values into the appropriate fields:
    | Property | Value |
    | Name | Accounting Local Disks |
    | Disk Type | HDD |
    | Capacity | 3 TB |
    | Backup | 1 TB |
    | Archive | 0 TB |

2020-12-23 19:12 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +    > You can use the links in the **Software Assurance** section to learn more about the assurance that is available. There are similar links in subsequent sections.
YES! I like this tip consolidated in one place as @kalendelaney has proposed, rather than recommending that they follow the links after each step.

2020-12-23 19:23 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Under **Geo-redundant storage (GRS)**, ensure that the **GRS replicates your data to a secondary region that is hundreds of miles away from the primary region** slider is slid to the left.
How about...
1. Under **Geo-redundant storage (GRS)**, ensure that the toggle beside **GRS replicates your data to a secondary region that is hundreds of miles away from the primary region** is turned off.

2020-12-23 19:25 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Under **Virtual Machine costs**, ensure that the **Enable this for the Calculator to not recommend B-series virtual machines** slider is slid to the left.
How about...
1. Under **Virtual Machine costs**, ensure that the toggle beside **Enable this for the Calculator to not recommend B-series virtual machines** is turned off.

2020-12-23 19:29 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Under **Storage costs**, leave all the values at their defaults.
How about...
1. Under **Storage costs**, keep all default values.

2020-12-23 19:33 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Under **Other assumption**, expand each section and look at the associated costs.
How about...

1. Under **Other assumption**, expand each section and examine the associated costs.

2020-12-23 19:35 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. At the bottom of the page, select **Next**.
Yes, I like this step to end Task 12!

2020-12-23 19:40 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Scroll down the report and investigate the estimated breakdown of costs for on-premises systems and Azure. Make a note of this information:
How about....

1. Scroll down to display the report and examine the estimated costs for on-premises systems compared to Azure. Make a note of this information:

2020-12-23 19:52 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Scroll down the report and investigate the estimated breakdown of costs for on-premises systems and Azure. Make a note of this information:
I think that it might be helpful to add content about changing the region since that can have such a great impact upon price.

How about this...
Change the region based on your location, network latency, or data sovereignty requirements, and examine how the costs compare.

2020-12-23 20:34 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +After completing this exercise, you have used the Azure TCO calculator to identify cost differences between on-premises and Azure deployments for Adatum Corporation's Accounting server and its associ
The scenario says that we are a senior data engineer at AdventureWorks, not Adatum.

2020-12-23 20:38 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +In this exercise, you will perform examine the server that you are working with to understand the specs of the machine.
How about...
In this exercise, you will examine the specifications of your existing server.

2020-12-23 20:48 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +1. Determine the amount of memory that is being used
How about...
1. Identify the amount of memory used by the existing server
1. Discover the type of CPU of the existing server
1. Determine the disk configuration of the existing server

2020-12-23 21:04 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> -> **Hint**: Use the System information tools to capture this information
How about...
> **Hint**: You can use System Information, an application included in all modern versions of Windows, to obtain specifications about your server or desktop device. To open System Information, select Start, and enter System Information into search field.

2020-12-23 21:17 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +    > **Hint**: Use the System Information tools to capture this information
In the past, the Microsoft Style Guide (https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/computer-device-terms) instructed authors not to use terms that could be associated with violence since they don't always translate well to other languages. I don't see that in the latest version. However, it seems that anywhere we have "capture", we might be able to replace with "collect" or "obtain".

2020-12-23 21:20 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +After completing this exercise, you have collected information on the hardware specs of the server.
After completing this exercise, you will have collected information on the hardware specifications of the server.

2020-12-23 21:22 UTC, llarkan commented on Instruction/dp-050-01_instructions.md
> +The tasks for this exercise are:
How about:
The tasks for this exercise are as follows:

2021-01-04 12:03 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> -   - SQL Server 2008/2008R2 **True**
Fixed.

2021-01-04 12:04 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +The main tasks for this exercise are:
Done.

2021-01-04 12:09 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
>  1. Open the Microsoft Total Cost of Ownership (TCO) Calculator
Hi @llarkan, this is a markdown thing. The recommended working method is to code "1." for all ordered steps. The renderer then automatically numbers them correctly. If you see numbers other than "1.", that's incorrect, strictly speaking although the renderer usually numbers them correctly anyway. Have a look at the guide here: [Mastering Markdown](https://guides.github.com/features/mastering-markdown/ )

2021-01-04 12:49 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
Fixed.

2021-01-04 12:50 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
>  1. Choose any method of your choice to determine how much memory is being used on the server.
Done.

2021-01-04 12:51 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Choose any method of your choice to determine how CPU resources are being used on the server.
Done.

2021-01-04 12:51 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Choose any method of your choice to determine the disk configuration that is configured on the server.
Done

2021-01-04 12:52 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +      The customer has an application that uses many databases currently residing in an on-premises version of Microsoft SQL Server 2008. The total database footprint is large at 12 TB, and rapidly g
Done.

2021-01-04 12:56 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +      The customer in this example has a SQL Server that stores databases that fulfil departmental needs. The server on which the databases are hosted is a quad core server, with 16 GB of memory, and
Done.

2021-01-04 12:58 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +After completing this exercise, you have identified the appropriate database technologies to migrate to.
Done.

2021-01-04 14:16 UTC, alistairmatthews commented on Instruction/dp-050-02_instructions.md
> +You are the senior data engineer of AdventureWorks and are preparing for a data modernization project. You will begin by performing an inventory of the SQL Servers that exist in your environment usin
Done.

2021-01-04 14:20 UTC, alistairmatthews commented on Instruction/dp-050-02_instructions.md
> -1. On the windows desktop, click on **Start**, and type Microsoft Assessment, then click on **Microsoft Assessment and Planning Toolkit**
Hi @llarkan, All the text highlighted in red has been deleted in this pull request. In this case, it's because MAP is deprecated. So you only need to review green and white backgrounded text. Thanks!

2021-01-04 14:23 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. In the **Name** textbox, type **Accounting Local Disks**, and then enter these values:
Done.

2021-01-04 14:26 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +    > You can use the links in the **Software Assurance** section to learn more about the assurance that is available. There are similar links in subsequent sections.
Fixed.

2021-01-04 14:27 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Under **Geo-redundant storage (GRS)**, ensure that the **GRS replicates your data to a secondary region that is hundreds of miles away from the primary region** slider is slid to the left.
Done.

2021-01-04 14:27 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Under **Virtual Machine costs**, ensure that the **Enable this for the Calculator to not recommend B-series virtual machines** slider is slid to the left.
Done.

2021-01-04 14:28 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Under **Storage costs**, leave all the values at their defaults.
Done.

2021-01-04 14:28 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Under **IT labor costs**, leave all the values at their defaults.
Done

2021-01-04 14:29 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Under **Other assumption**, expand each section and look at the associated costs.
Done.

2021-01-04 14:30 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Scroll down the report and investigate the estimated breakdown of costs for on-premises systems and Azure. Make a note of this information:
Done.

2021-01-04 14:32 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Scroll down the report and investigate the estimated breakdown of costs for on-premises systems and Azure. Make a note of this information:
Done. I've added an extra step.

2021-01-04 14:33 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +After completing this exercise, you have used the Azure TCO calculator to identify cost differences between on-premises and Azure deployments for Adatum Corporation's Accounting server and its associ
Fixed.

2021-01-04 14:34 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +In this exercise, you will perform examine the server that you are working with to understand the specs of the machine.
Fixed.

2021-01-04 14:35 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Determine the amount of memory that is being used
Done.

2021-01-04 14:36 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> -> **Hint**: Use the System information tools to capture this information
Done.

2021-01-04 14:37 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +    > **Hint**: Use the System Information tools to capture this information
Noted. Thanks!

2021-01-04 14:38 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +After completing this exercise, you have collected information on the hardware specs of the server.
Done.

2021-01-04 14:38 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +The tasks for this exercise are:
Done.

2021-01-04 14:47 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Open your browser and navigate to [Azure TCO Calculator](https://azure.microsoft.com/pricing/tco/calculator/).
Hi @llarkan, I believe that T tool only works within Labs on Demand. As these labs aren't hosted there, we can't do that formatting.

2021-01-04 14:50 UTC, alistairmatthews commented on Instruction/dp-050-02_instructions.md
> -1. Open up your web browser and go to the [Microsoft Assessment and Planning Toolkit download site](https://www.microsoft.com/en-us/download/details.aspx?id=7826)
Again, this red text has already been deleted and the "T" tool won't work here. Thanks!

2021-01-04 15:06 UTC, alistairmatthews commented on Instruction/dp-050-01_instructions.md
> +1. Open your browser and navigate to [Azure TCO Calculator](https://azure.microsoft.com/pricing/tco/calculator/).
My mistake - this one is hosted in LODs, it's DP060 that isn't. I've added the +++ syntax that should enable this.

2021-01-04 16:02 UTC, alistairmatthews commented
> 
> 
> This looks great, and I see that others have already provided some terrific feedback! My comments are based upon the changes that have already been proposed.
> 
> I'm new to proposing changes in GitHub, and I'm sorry for the additional work that it must create for the approvers.
> 
> Thanks.

2021-02-01 17:31 UTC, merged

2021-02-01 17:31 UTC, rcaper commented
Merged